image:
  repository: ghcr.io/fritzduchardt/finclaw
  tag: "main"
  pullPolicy: always
env:
  - name: RAPID
    value: "<path:kv/data/finclaw#rapid>"
  - name: TWELVE_DATA
    value: "<path:kv/data/finclaw#twelveData>"
